from flask import Flask
from celery import Celery
from config import broker_url, flask_secret_key
from playhouse.db_url import connect
import locale
from config import database as cfg_database
from flask_login import LoginManager

# russian month and etc
locale.setlocale(locale.LC_ALL, 'ru_RU.utf8')

app = Flask(__name__)

app.config['CELERY_BROKER_URL'] = broker_url
login = LoginManager(app)
login.login_view = 'login'
app.config['SECRET_KEY'] = flask_secret_key

celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'])
celery.conf.update(app.config)
database = connect(cfg_database)


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    database.connect()


# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not database.is_closed():
        database.close()


if __name__ == '__main__':
    pass
